name: Build StarStudio

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install dependencies
        run: |
          choco install premake

      - name: Generate project files with Premake
        run: premake5 vs2022

      - name: Build project with MSBuild
        run: MSBuild /m /p:Configuration=Debug StarStudio.sln

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: StarStudio-Windows
          path: "**/Sandbox/Sandbox.exe"