name: Build StarEngine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Checkout correct commit for GLFW submodule
        run: |
          cd StarEngine/vendor/GLFW
          git fetch origin f48003349257c49ddc0e3d8a31d1f2d25d1585f7
          git checkout f48003349257c49ddc0e3d8a31d1f2d25d1585f7

      - name: Checkout correct commit for ImGui submodule
        run: |
          cd StarEngine/vendor/imgui
          git fetch origin 0cfb1e23348b1fd480714eed212c21d913fee27c
          git checkout 0cfb1e23348b1fd480714eed212c21d913fee27c

      - name: Checkout correct commit for yaml-cpp submodule
        run: |
          cd StarEngine/vendor/yaml-cpp
          git fetch origin ceb728371d88def1b26a03d8e15cba42c9509d4f
          git checkout ceb728371d88def1b26a03d8e15cba42c9509d4f

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta4"

      - name: Fetch Vulkan SDK version spec
        shell: bash
        run: |
          curl -o config.json https://vulkan.lunarg.com/sdk/config/1.4.304.0/windows/config.json
      
      - name: Configure Vulkan SDK using the downloaded spec
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-config-file: config
          vulkan-components: Vulkan-Headers, Vulkan-Loader, SPIRV-Cross, SPIRV-Tools, SPIRV-Headers
          vulkan-use-cache: true

      - name: Generate project files with Premake
        run: premake5 vs2022

      - name: Build project with MSBuild
        run: MSBuild /m /p:Configuration=Debug StarEngine.sln

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: StarEngine-Windows
          path: "bin/Debug-windows-x86_64/**/**.exe"
