name: Build StarEngine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  SOLUTION_FILE_PATH: StarEngine.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release, Dist]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'starbounded-dev/StarEngine'
          submodules: true
          lfs: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.2.0
        with:
          vulkan_version: 1.3.296.0
          optional_components: com.lunarg.vulkan.vma, com.lunarg.vulkan.debug, com.lunarg.vulkan.glm
          install_runtime: true
          cache: true
          stripdown: true
          
          install_swiftshader: false
          install_lavapipe: false

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: 'x64'
      
      - name: Setup
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cd scripts
          python SetupAction.py

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          MSBuild ${{env.SOLUTION_FILE_PATH}} /m /p:Configuration=${{ matrix.build-configuration }} -fl -flp:logfile=logs/Build-${{ matrix.build-configuration }}.log
          
