name: Build StarEngine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Checkout correct commit for GLFW submodule
        run: |
          cd StarEngine/vendor/GLFW
          git fetch origin f48003349257c49ddc0e3d8a31d1f2d25d1585f7
          git checkout f48003349257c49ddc0e3d8a31d1f2d25d1585f7

      - name: Checkout correct commit for ImGui submodule
        run: |
          cd StarEngine/vendor/imgui
          git fetch origin 0cfb1e23348b1fd480714eed212c21d913fee27c
          git checkout 0cfb1e23348b1fd480714eed212c21d913fee27c

      - name: Checkout correct commit for yaml-cpp submodule
        run: |
          cd StarEngine/vendor/yaml-cpp
          git fetch origin ceb728371d88def1b26a03d8e15cba42c9509d4f
          git checkout ceb728371d88def1b26a03d8e15cba42c9509d4f

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.2.0
        with:
          # You can set the Vulkan SDK version to download.
          # Defaults to latest version, if version not set.
          vulkan_version: 1.3.296.0
          optional_components: com.lunarg.vulkan.vma, com.lunarg.vulkan.debug, com.lunarg.vulkan.glm
          install_runtime: true
          cache: true
          stripdown: true
          
          install_swiftshader: false
          install_lavapipe: false

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta4"

      - name: Generate project files with Premake
        run: premake5 vs2022

      - name: Build project with MSBuild
        run: MSBuild /m /p:Configuration=Dist StarEngine.sln

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: StarEngine-Windows
          path: |
            bin/Dist-windows-x86_64/StarEditor/StarEditor.exe
            bin/Dist-windows-x86_64/StarEditor/assets
            bin/Dist-windows-x86_64/StarEditor/Resources
            bin/Dist-windows-x86_64/StarEditor/imgui.ini
