name: C/C++ PreMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
  
    - uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta4"

    - name: pull
      run: git pull origin main --recurse-submodules

  
    - name: premake
      run: premake5 vs2022

    - name: compile to exe
      run: msbuild /p:Configuration=Debug StarStudio.sln

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: bin/Debug-windows-x86_6/Sandbox/Sandbox.exe
