name: Build StarStudio

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Premake
        run: |
          Invoke-WebRequest -Uri "https://github.com/premake/premake-core/releases/download/v5.0.0-beta4/premake-5.0.0-beta4-windows.zip" -OutFile premake.zip
          Expand-Archive premake.zip -DestinationPath .
          echo "$(pwd)\premake5.exe" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Generate project files with Premake
        run: premake5 vs2022

      - name: Build project with MSBuild
        run: MSBuild /m /p:Configuration=Debug StarStudio.sln

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: StarStudio-Windows
          path: "**/Sandbox/Sandbox.exe"